### ISSUE TITLE
Add support for running natively on QNAP NAS

### ISSUE THREAD

**Issue by 0ddb0d** [oddstr13/jellyfin-fixup-scripts#3]
**UPDATE** [It's definitely a Jellyfin bug.](https://github.com/jellyfin/jellyfin/issues/1410)

Follow up from [https://github.com/jellyfin/jellyfin/pull/1338](url), sorry about the wait.

Prerequisites:-

- Jellyfin 10.3.3.0 x86_64 installed from [Qnapclub](https://www.qnapclub.eu/en/qpkg/693)

- [Entware](https://github.com/Entware/Entware/wiki/Install-on-QNAP-NAS) - necessary for an up to date Python3 and proper ps

- Python3 package from Entware

- procps-ng-ps package from Entware

- library.db is located at /share/CACHEDEV2_DATA/.qpkg/Jellyfin/DB/data

After running the script, a user with the "Enable access to all libraries" permission enabled can see the items in a collection however any user without this permission sees empty collections.

As a test I tried creating a new user with permissions set like this:

![image](https://user-images.githubusercontent.com/45958107/58963784-1e7eb800-87f1-11e9-9af9-462336876404.png)

The result was the same, no items listed under collections.

![image](https://user-images.githubusercontent.com/45958107/58964089-a6fd5880-87f1-11e9-9132-4edb7ae7b4dc.png)

If I set "Enable access to all libraries" for this user everything shows up correctly, suggesting the fault is not in your script but in Jellyfin itself.

**Important note about QNAP NAS devices**

Since I have no idea how much you know about QNAP devices I should point out that the system volume path i.e. /share/CACHEDEV2_DATA only applies to systems with an identical RAID configuration to mine, you can't just assume that it will be the same for everyone. To find where Jellyfin has been installed on a QNAP NAS it is necessary to use `/sbin/getcfg Jellyfin Install_Path -f /etc/config/qpkg.conf`

**Comment by oddstr13** [comment]
The "access to all libraries" issue should be solved with the latest release of Jellyfin - https://github.com/jellyfin/jellyfin/releases/tag/v10.3.4

**Comment by 0ddb0d** [comment]
Unfortunately 10.3.5 did not fix the underlying Jellyfin bug. I would like to close this as the script works fine and is clearly not the cause.

Any objections?

**Comment by oddstr13** [comment]
Keep it open for now to track QNAP support

**Comment by 0ddb0d** [comment]
Update: The collections bug no longer occurs in Jellyfin 10.3.6
